name: Sync Aliyun to Docker Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: crpi-uxhqadilenvgjaqm.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sync Image via Skopeo
        run: |
          skopeo copy \
            docker://crpi-uxhqadilenvgjaqm.cn-hangzhou.personal.cr.aliyuncs.com/skylinecorp/forecasting:latest \
            docker://docker.io/skylinecorp/forecasting:latest
